# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure Pass - Sponsorship(91d5a716-b2a7-41f5-862b-148f7a30f56a)'
    backendAzureRmResourceGroupName: 'aks-new-rg'
    backendAzureRmStorageAccountName: 'abiodunstorage'
    backendAzureRmContainerName: 'terracont'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV4@4
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure Pass - Sponsorship(91d5a716-b2a7-41f5-862b-148f7a30f56a)'

- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Azure Pass - Sponsorship(91d5a716-b2a7-41f5-862b-148f7a30f56a)'